import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import bcrypt from "bcryptjs";
import { randomBytes } from "node:crypto";
import path from "path";

const rawUrl = process.env.DATABASE_URL ?? `file:${path.join(process.cwd(), "prisma", "dev.db")}`;
const adapter = new PrismaBetterSqlite3({ url: rawUrl });
const prisma = new PrismaClient({ adapter });

// Anonymized fixtures. These are intentionally generic placeholder names so
// that no real parishioner data is ever committed to the repo. Passwords are
// generated per seed run and printed at the end.
const generatePassword = () => randomBytes(9).toString("base64url");

const CATECHIST_FIXTURES = [
  { name: "Demo Catechist 01", email: "catechist01@example.test" },
  { name: "Demo Catechist 02", email: "catechist02@example.test" },
  { name: "Demo Catechist 03", email: "catechist03@example.test" },
  { name: "Demo Catechist 04", email: "catechist04@example.test" },
  { name: "Demo Catechist 05", email: "catechist05@example.test" },
];

const STUDENT_FIXTURES: Array<{ firstName: string; lastName: string; gradeLevel: string; dob: string }> = [
  { firstName: "Student", lastName: "Alpha", gradeLevel: "GRADE_2", dob: "2016-03-15" },
  { firstName: "Student", lastName: "Beta", gradeLevel: "GRADE_2", dob: "2016-07-22" },
  { firstName: "Student", lastName: "Gamma", gradeLevel: "GRADE_8", dob: "2010-01-14" },
  { firstName: "Student", lastName: "Delta", gradeLevel: "GRADE_8", dob: "2010-05-30" },
  { firstName: "Student", lastName: "Epsilon", gradeLevel: "GRADE_5", dob: "2013-02-19" },
  { firstName: "Student", lastName: "Zeta", gradeLevel: "KINDERGARTEN", dob: "2018-06-14" },
];

async function main() {
  console.log("Seeding anonymized demo data...");
  const credentials: Array<{ role: string; email: string; password: string }> = [];

  const adminPass = generatePassword();
  const admin = await prisma.user.upsert({
    where: { email: "admin@example.test" },
    update: {},
    create: {
      name: "Demo Admin",
      email: "admin@example.test",
      password: await bcrypt.hash(adminPass, 12),
      role: "ADMIN",
    },
  });
  credentials.push({ role: "ADMIN", email: admin.email, password: adminPass });

  const directorPass = generatePassword();
  const director = await prisma.user.upsert({
    where: { email: "director@example.test" },
    update: {},
    create: {
      name: "Demo Director",
      email: "director@example.test",
      password: await bcrypt.hash(directorPass, 12),
      role: "DIRECTOR",
    },
  });
  credentials.push({ role: "DIRECTOR", email: director.email, password: directorPass });

  for (const c of CATECHIST_FIXTURES) {
    const pass = generatePassword();
    await prisma.user.upsert({
      where: { email: c.email },
      update: {},
      create: {
        name: c.name,
        email: c.email,
        password: await bcrypt.hash(pass, 12),
        role: "CATECHIST",
        catechist: {
          create: {
            certifications: JSON.stringify(["Safe Environment Training"]),
          },
        },
      },
    });
    credentials.push({ role: "CATECHIST", email: c.email, password: pass });
  }

  for (const s of STUDENT_FIXTURES) {
    await prisma.student.create({
      data: {
        firstName: s.firstName,
        lastName: s.lastName,
        gradeLevel: s.gradeLevel as never,
        dateOfBirth: new Date(s.dob),
      },
    });
  }

  console.log("\nSeed complete. Credentials below — store securely, do not commit:");
  for (const c of credentials) {
    console.log(`  ${c.role.padEnd(10)} ${c.email.padEnd(32)} ${c.password}`);
  }
  console.log("\nNote: this seed creates ANONYMIZED demo data only. Do not edit this file");
  console.log("to embed real parishioner names, emails, or passwords.");
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
