import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "path";

const rawUrl = process.env.DATABASE_URL ?? `file:${path.join(process.cwd(), "prisma", "dev.db")}`;
const adapter = new PrismaBetterSqlite3({ url: rawUrl });
const prisma = new PrismaClient({ adapter });

type LessonInput = {
  lessonNumber: number;
  title: string;
  objective: string;
  scriptureRef: string;
  cccParagraphs: string;
  materials: string[];
  activities: string[];
  prayerFocus: string;
  takeHome: string;
  durationMinutes?: number;
};

type UnitInput = {
  gradeLevel: string;
  program: string;
  unitNumber: number;
  title: string;
  description: string;
  cccReference: string;
  lessons: LessonInput[];
};

const curriculum: UnitInput[] = [
  // ===== PRE-K =====
  {
    gradeLevel: "PRE_K",
    program: "Pre-K Faith Formation",
    unitNumber: 1,
    title: "God Made Me",
    description: "Children discover that God lovingly created each of them and that they are special to God.",
    cccReference: "CCC 279-301",
    lessons: [
      {
        lessonNumber: 1,
        title: "God Created the World",
        objective: "Children will learn that God made everything in the world because He loves us.",
        scriptureRef: "Genesis 1:1",
        cccParagraphs: "CCC 279-281",
        materials: ["Bible", "Creation coloring pages", "Crayons", "Stickers"],
        activities: ["Listen to the Creation story", "Color a creation scene", "Name things God made"],
        prayerFocus: "Thank you, God, for making our beautiful world!",
        takeHome: "Go on a nature walk with your family and find 5 things God made.",
      },
      {
        lessonNumber: 2,
        title: "God Made Me Special",
        objective: "Children will understand that God made each person unique and special.",
        scriptureRef: "Psalm 139:14",
        cccParagraphs: "CCC 355-357",
        materials: ["Mirror", "Self-portrait paper", "Crayons", "Handout: 'I Am Special' worksheet"],
        activities: ["Draw a self-portrait", "Share one thing that makes you special", "Sing 'God Made Me'"],
        prayerFocus: "God, thank you for making me!",
        takeHome: "Draw a picture of yourself and write your name. Tell your parents what makes you special.",
      },
      {
        lessonNumber: 3,
        title: "My Body is a Gift",
        objective: "Children will appreciate their bodies as gifts from God and learn to care for them.",
        scriptureRef: "1 Corinthians 6:19",
        cccParagraphs: "CCC 364-365",
        materials: ["Body outline handout", "Crayons", "Stickers", "Song: 'Head, Shoulders, Knees and Toes'"],
        activities: ["Sing and move to body song", "Color and label body parts", "Discuss how we care for our bodies"],
        prayerFocus: "Thank you, God, for my healthy body. Help me take good care of it.",
        takeHome: "Practice saying a prayer before bed, thanking God for your body.",
      },
    ],
  },
  {
    gradeLevel: "PRE_K",
    program: "Pre-K Faith Formation",
    unitNumber: 2,
    title: "God Loves Me",
    description: "Children explore the infinite, unconditional love God has for each of them.",
    cccReference: "CCC 218-221",
    lessons: [
      {
        lessonNumber: 1,
        title: "God's Love is Forever",
        objective: "Children will know that God loves them always, no matter what.",
        scriptureRef: "John 3:16",
        cccParagraphs: "CCC 218-221",
        materials: ["Heart-shaped paper", "Crayons", "Glitter glue", "Bible story cards"],
        activities: ["Make a heart craft", "Hear a story about God's love", "Give each other a hug"],
        prayerFocus: "God loves me so much! I love God too.",
        takeHome: "Give your family a big hug and tell them God loves them.",
      },
      {
        lessonNumber: 2,
        title: "God Cares for Me",
        objective: "Children will learn that God watches over and cares for them every day.",
        scriptureRef: "Matthew 6:26",
        cccParagraphs: "CCC 301-303",
        materials: ["Birds and flowers picture cards", "Coloring sheet", "Crayons"],
        activities: ["Look at creation pictures", "Hear how God cares for birds and flowers", "Draw something God cares for"],
        prayerFocus: "God, thank you for taking care of me every day.",
        takeHome: "Look outside for birds or flowers and remember that God cares for you even more.",
      },
      {
        lessonNumber: 3,
        title: "We Are God's Family",
        objective: "Children will discover that all people are God's children and we belong to His family.",
        scriptureRef: "1 John 3:1",
        cccParagraphs: "CCC 1702-1706",
        materials: ["Family photo pages", "Crayons", "Handout: 'God's Big Family'"],
        activities: ["Draw your family", "Talk about what families do", "Make a class 'God's Family' display"],
        prayerFocus: "Thank you, God, for my family and for making us all Your children.",
        takeHome: "Ask your parents to tell you about your Baptism day — when you joined God's family.",
      },
    ],
  },
  {
    gradeLevel: "PRE_K",
    program: "Pre-K Faith Formation",
    unitNumber: 3,
    title: "Jesus Is My Friend",
    description: "Children meet Jesus as a loving friend who cares for them.",
    cccReference: "CCC 422-451",
    lessons: [
      {
        lessonNumber: 1,
        title: "Who is Jesus?",
        objective: "Children will learn that Jesus is the Son of God who came to love and save us.",
        scriptureRef: "Luke 2:11",
        cccParagraphs: "CCC 422-424",
        materials: ["Nativity picture", "Bible story book", "Baby Jesus coloring page", "Crayons"],
        activities: ["Hear the Christmas story", "Color baby Jesus", "Sing 'Away in a Manger'"],
        prayerFocus: "Jesus, I am so glad you came to be with us. You are my friend.",
        takeHome: "Ask your parents to read you the Christmas story from the Bible before bed.",
      },
      {
        lessonNumber: 2,
        title: "Jesus Loves Children",
        objective: "Children will know that Jesus especially loves and welcomes children.",
        scriptureRef: "Mark 10:14",
        cccParagraphs: "CCC 1244",
        materials: ["Gospel story cards", "Coloring sheet of Jesus with children", "Crayons"],
        activities: ["Hear the story of Jesus blessing children", "Color Jesus with children", "Act out the story"],
        prayerFocus: "Jesus, thank you for loving me. I love you too!",
        takeHome: "Draw a picture of you and Jesus as friends. Share it with your family.",
      },
      {
        lessonNumber: 3,
        title: "Jesus Is Always With Me",
        objective: "Children will find comfort knowing Jesus is always present with them.",
        scriptureRef: "Matthew 28:20",
        cccParagraphs: "CCC 645-646",
        materials: ["Heart badge craft supplies", "Stickers", "Crayons"],
        activities: ["Make a 'Jesus is with me' heart badge", "Share times they feel scared or alone", "Learn a simple prayer"],
        prayerFocus: "Jesus, be with me when I am scared. I know you are always there.",
        takeHome: "When you feel scared at night, say: 'Jesus, I know you are with me.'",
      },
    ],
  },
  {
    gradeLevel: "PRE_K",
    program: "Pre-K Faith Formation",
    unitNumber: 4,
    title: "We Pray Together",
    description: "Children learn what prayer is and practice simple ways to talk with God.",
    cccReference: "CCC 2558-2565",
    lessons: [
      {
        lessonNumber: 1,
        title: "Talking to God",
        objective: "Children will understand that prayer is talking and listening to God.",
        scriptureRef: "Philippians 4:6",
        cccParagraphs: "CCC 2558-2562",
        materials: ["Prayer hands craft", "Construction paper", "Crayons", "Glue"],
        activities: ["Trace prayer hands", "Practice quiet listening", "Say a simple thank-you prayer together"],
        prayerFocus: "God, I want to talk to you. Thank you for listening to me.",
        takeHome: "Tell your family one thing you want to thank God for today.",
      },
      {
        lessonNumber: 2,
        title: "The Sign of the Cross",
        objective: "Children will learn and practice making the Sign of the Cross.",
        scriptureRef: "Matthew 28:19",
        cccParagraphs: "CCC 232-237",
        materials: ["Sign of the Cross poster", "Small crosses", "Stickers"],
        activities: ["Learn the Sign of the Cross step by step", "Practice together", "Decorate a small cross to take home"],
        prayerFocus: "In the name of the Father, and of the Son, and of the Holy Spirit. Amen.",
        takeHome: "Teach your family the Sign of the Cross. Practice it before meals.",
      },
      {
        lessonNumber: 3,
        title: "Grace Before Meals",
        objective: "Children will learn to thank God for food through mealtime prayer.",
        scriptureRef: "Psalm 136:25",
        cccParagraphs: "CCC 2698",
        materials: ["Prayer card with 'Bless Us O Lord'", "Food pictures", "Crayons"],
        activities: ["Learn 'Bless Us O Lord'", "Pretend meal prayer practice", "Draw favorite foods to be thankful for"],
        prayerFocus: "Bless us, O Lord, and these Thy gifts which we are about to receive from Thy bounty, through Christ our Lord. Amen.",
        takeHome: "Pray before every meal this week with your family.",
      },
      {
        lessonNumber: 4,
        title: "Praying at Church",
        objective: "Children will learn about prayer at church and in Mass.",
        scriptureRef: "Luke 18:1",
        cccParagraphs: "CCC 1345-1347",
        materials: ["Picture of church interior", "Activity sheet", "Crayons"],
        activities: ["Look at pictures of church", "Learn what happens at Mass", "Draw their own church"],
        prayerFocus: "God, I love coming to your house to pray with my family.",
        takeHome: "At Mass this Sunday, point out something new you noticed to your parents.",
      },
    ],
  },

  // ===== KINDERGARTEN =====
  {
    gradeLevel: "KINDERGARTEN",
    program: "Elementary Faith Formation",
    unitNumber: 1,
    title: "God Our Creator",
    description: "Kindergarteners explore how God created the world, humanity, and all living things out of love.",
    cccReference: "CCC 279-324",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Story of Creation",
        objective: "Students will retell the seven days of creation and know that God made everything good.",
        scriptureRef: "Genesis 1:1-31",
        cccParagraphs: "CCC 279-289",
        materials: ["Bible", "Creation story flip book", "Crayons", "Scissors"],
        activities: ["Read Genesis creation story", "Make a 7-day creation flip book", "Act out the days of creation"],
        prayerFocus: "Lord, you made everything good and beautiful. Thank you!",
        takeHome: "Draw the day of creation that is your favorite. Tell your family why.",
      },
      {
        lessonNumber: 2,
        title: "Adam, Eve, and the Garden",
        objective: "Students will learn about God's first human family and how He cares for us.",
        scriptureRef: "Genesis 2:7-9, 15",
        cccParagraphs: "CCC 355-379",
        materials: ["Garden of Eden illustration", "Playdough (to form shapes)", "Activity sheet"],
        activities: ["Hear the story of Adam and Eve", "Create animals with playdough", "Discuss how we care for creation"],
        prayerFocus: "Lord, help me take care of the world you gave us.",
        takeHome: "Plant a seed or water a plant at home. Thank God for the earth.",
      },
      {
        lessonNumber: 3,
        title: "God Never Stops Loving Us",
        objective: "Students will understand that even when we sin, God's love never ends.",
        scriptureRef: "Romans 8:38-39",
        cccParagraphs: "CCC 385-390",
        materials: ["Story of the Prodigal Son picture book", "Heart activity sheet"],
        activities: ["Hear the Prodigal Son story (simplified)", "Complete a heart puzzle", "Talk about saying sorry"],
        prayerFocus: "God, thank you for always loving me even when I make mistakes.",
        takeHome: "Say sorry to someone this week and experience God's forgiveness through them.",
      },
    ],
  },
  {
    gradeLevel: "KINDERGARTEN",
    program: "Elementary Faith Formation",
    unitNumber: 2,
    title: "Jesus Our Savior",
    description: "Children learn the story of Jesus — His birth, life, death, and resurrection.",
    cccReference: "CCC 422-682",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Birth of Jesus",
        objective: "Students will know the Christmas story and why Jesus came to earth.",
        scriptureRef: "Luke 2:1-20",
        cccParagraphs: "CCC 525-526",
        materials: ["Nativity set", "Nativity coloring page", "Crayons", "Star craft supplies"],
        activities: ["Arrange the nativity scene", "Hear Luke 2:1-20", "Make a star ornament"],
        prayerFocus: "Baby Jesus, we are so glad you came. Thank you for being born for us.",
        takeHome: "Set up a nativity at home. Pray with your family in front of it.",
      },
      {
        lessonNumber: 2,
        title: "Jesus Heals and Helps",
        objective: "Students will learn that Jesus showed God's love by healing people and helping the poor.",
        scriptureRef: "Mark 10:46-52",
        cccParagraphs: "CCC 547-550",
        materials: ["Healing stories picture book", "Activity sheet", "Crayons"],
        activities: ["Hear healing miracles of Jesus", "Role-play helping someone in need", "Draw someone Jesus healed"],
        prayerFocus: "Jesus, help me show your love to people who need help.",
        takeHome: "Do one kind thing for someone at home this week.",
      },
      {
        lessonNumber: 3,
        title: "Jesus Died and Rose Again",
        objective: "Students will know the basic story of Jesus's death and resurrection.",
        scriptureRef: "Luke 24:1-12",
        cccParagraphs: "CCC 595-658",
        materials: ["Easter story picture book", "Butterfly craft supplies"],
        activities: ["Hear Easter story (age-appropriate)", "Make a resurrection butterfly craft", "Sing an Easter song"],
        prayerFocus: "Alleluia! Jesus, you rose from the dead because you love us!",
        takeHome: "Ask your parents to tell you about Easter and what your family does to celebrate.",
      },
    ],
  },
  {
    gradeLevel: "KINDERGARTEN",
    program: "Elementary Faith Formation",
    unitNumber: 3,
    title: "The Holy Spirit",
    description: "Children discover the Holy Spirit as God's gift to help and guide us.",
    cccReference: "CCC 683-747",
    lessons: [
      {
        lessonNumber: 1,
        title: "Who is the Holy Spirit?",
        objective: "Students will know that the Holy Spirit is God and is with us always.",
        scriptureRef: "John 14:26",
        cccParagraphs: "CCC 683-690",
        materials: ["Dove craft supplies", "Wind pinwheel", "Holy Spirit symbols poster"],
        activities: ["Explore symbols of the Holy Spirit (wind, dove, fire)", "Make a dove craft", "Discuss how the Spirit helps us"],
        prayerFocus: "Come, Holy Spirit, fill my heart with your love.",
        takeHome: "Ask your parents about your Baptism — when the Holy Spirit came to live in you.",
      },
      {
        lessonNumber: 2,
        title: "Pentecost: The Holy Spirit Comes",
        objective: "Students will hear the Pentecost story and know the Spirit was given to the Church.",
        scriptureRef: "Acts 2:1-4",
        cccParagraphs: "CCC 731-741",
        materials: ["Pentecost flame craft supplies", "Orange and red tissue paper"],
        activities: ["Hear the Pentecost story", "Make flame headbands with tissue paper", "Discuss how the Spirit makes us brave"],
        prayerFocus: "Holy Spirit, help me be brave and share God's love.",
        takeHome: "Draw the Holy Spirit's fire coming down on the apostles. Share it at Mass.",
      },
    ],
  },
  {
    gradeLevel: "KINDERGARTEN",
    program: "Elementary Faith Formation",
    unitNumber: 4,
    title: "Living as God's Children",
    description: "Kindergarteners explore what it means to love God and neighbor in everyday life.",
    cccReference: "CCC 1699-1715",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Great Commandment",
        objective: "Students will learn Jesus's command to love God and love our neighbor.",
        scriptureRef: "Matthew 22:37-39",
        cccParagraphs: "CCC 1822-1829",
        materials: ["Heart display board", "Construction paper hearts", "Markers"],
        activities: ["Hear Matthew 22:37-39", "Write/draw one way to love God and one way to love neighbor", "Create a class love display"],
        prayerFocus: "Jesus, help me love God and love everyone I meet.",
        takeHome: "Do one loving thing for a neighbor or family member today.",
      },
      {
        lessonNumber: 2,
        title: "We Go to Church",
        objective: "Students will understand why Catholics go to Mass each Sunday.",
        scriptureRef: "Hebrews 10:25",
        cccParagraphs: "CCC 2180-2183",
        materials: ["Mass picture book", "Church drawing supplies"],
        activities: ["Discuss what they see at Mass", "Draw their church", "Learn basic Mass responses"],
        prayerFocus: "Lord, I love coming to Your house every Sunday.",
        takeHome: "At Mass this week, pay close attention to one special part. Tell your family about it.",
      },
      {
        lessonNumber: 3,
        title: "Sharing and Caring",
        objective: "Students will practice generosity and care for those in need.",
        scriptureRef: "Luke 21:1-4",
        cccParagraphs: "CCC 2443-2449",
        materials: ["Story of the Widow's Offering", "Coin collection box for donation", "Crayons"],
        activities: ["Hear the story of the widow's coin", "Bring a donation item from home", "Make thank-you cards for church helpers"],
        prayerFocus: "God, help me share what I have with others.",
        takeHome: "Find something at home to donate to those in need. Bring it next week.",
      },
    ],
  },

  // ===== GRADE 1 =====
  {
    gradeLevel: "GRADE_1",
    program: "Elementary Faith Formation",
    unitNumber: 1,
    title: "God's World",
    description: "First graders explore God as the loving creator of all things visible and invisible.",
    cccReference: "CCC 279-354",
    lessons: [
      {
        lessonNumber: 1,
        title: "God the Creator",
        objective: "Students will know that God created everything out of nothing and that creation is good.",
        scriptureRef: "Genesis 1:1, 31",
        cccParagraphs: "CCC 282-289",
        materials: ["Bible", "Creation booklet", "Colored pencils", "Nature items (leaves, stones)"],
        activities: ["Read creation account", "Create a 7-days booklet", "Explore nature items God made"],
        prayerFocus: "Lord of all creation, thank you for the world you made for us.",
        takeHome: "Spend 10 minutes outside appreciating creation. Write 3 things you are thankful for.",
      },
      {
        lessonNumber: 2,
        title: "Angels and Saints",
        objective: "Students will learn that God also created invisible beings (angels) who serve Him.",
        scriptureRef: "Psalm 91:11",
        cccParagraphs: "CCC 328-336",
        materials: ["Angel story book", "Angel craft supplies", "Guardian angel prayer card"],
        activities: ["Hear about guardian angels", "Make an angel craft", "Learn the Guardian Angel prayer"],
        prayerFocus: "Angel of God, my guardian dear, to whom God's love commits me here...",
        takeHome: "Pray the Guardian Angel prayer each morning this week.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_1",
    program: "Elementary Faith Formation",
    unitNumber: 2,
    title: "The Bible",
    description: "Students are introduced to Sacred Scripture as God's word written for us.",
    cccReference: "CCC 101-141",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Bible is God's Word",
        objective: "Students will know that the Bible is a special book where God speaks to us.",
        scriptureRef: "2 Timothy 3:16",
        cccParagraphs: "CCC 101-108",
        materials: ["Children's Bible", "Bible bookmarks to make", "Colored pencils"],
        activities: ["Handle and explore a Bible", "Learn Old and New Testament", "Decorate a personal Bible bookmark"],
        prayerFocus: "Lord, speak to me through your holy Word.",
        takeHome: "Ask your family to read one Bible story together this week.",
      },
      {
        lessonNumber: 2,
        title: "Stories from the Old Testament",
        objective: "Students will hear key Old Testament stories and their messages.",
        scriptureRef: "Psalm 23:1",
        cccParagraphs: "CCC 128-130",
        materials: ["Old Testament story cards (Noah, Moses, David)", "Craft supplies"],
        activities: ["Hear Noah, Moses, and David stories", "Match stories to their characters", "Draw a favorite story scene"],
        prayerFocus: "Lord, you have been faithful to your people throughout history. Thank you.",
        takeHome: "Tell your parents the story of Noah or Moses.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_1",
    program: "Elementary Faith Formation",
    unitNumber: 3,
    title: "Jesus the Teacher",
    description: "Students learn about Jesus's teachings and parables.",
    cccReference: "CCC 512-570",
    lessons: [
      {
        lessonNumber: 1,
        title: "Jesus Teaches with Parables",
        objective: "Students will understand that Jesus used stories (parables) to teach about God's Kingdom.",
        scriptureRef: "Matthew 13:3",
        cccParagraphs: "CCC 546",
        materials: ["Parable story books", "Activity sheets", "Crayons"],
        activities: ["Hear the Parable of the Sower", "Draw the four kinds of soil", "Discuss what good soil means for our hearts"],
        prayerFocus: "Jesus, help my heart be good soil so your word can grow in me.",
        takeHome: "Tell someone the Parable of the Sower. What kind of soil do you want to be?",
      },
      {
        lessonNumber: 2,
        title: "The Sermon on the Mount",
        objective: "Students will be introduced to the Beatitudes as Jesus's recipe for happiness.",
        scriptureRef: "Matthew 5:3-10",
        cccParagraphs: "CCC 1716-1724",
        materials: ["Beatitudes poster", "Activity sheet", "Crayons"],
        activities: ["Read the Beatitudes together", "Match Beatitudes to pictures", "Discuss what 'blessed' means"],
        prayerFocus: "Lord, help me live the Beatitudes every day.",
        takeHome: "Pick one Beatitude. Try to live it this week.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_1",
    program: "Elementary Faith Formation",
    unitNumber: 4,
    title: "Sacraments of Initiation",
    description: "Students are introduced to Baptism, Confirmation, and Eucharist as the three sacraments that make us full members of the Church.",
    cccReference: "CCC 1212-1419",
    lessons: [
      {
        lessonNumber: 1,
        title: "Baptism: We Belong to God",
        objective: "Students will understand that Baptism makes us children of God and members of the Church.",
        scriptureRef: "Matthew 28:19",
        cccParagraphs: "CCC 1213-1284",
        materials: ["Baptism photos (bring from home)", "Baptismal candle craft", "Blue and white paper"],
        activities: ["Share Baptism photos/stories", "Learn about water, oil, and light in Baptism", "Make a Baptism candle craft"],
        prayerFocus: "Thank you, God, for making me your child in Baptism.",
        takeHome: "Ask your parents to tell you about your Baptism day. Look at photos together.",
      },
      {
        lessonNumber: 2,
        title: "First Communion: Jesus's Gift",
        objective: "Students will be introduced to the Eucharist as Jesus truly present in the Host.",
        scriptureRef: "John 6:35",
        cccParagraphs: "CCC 1322-1419",
        materials: ["Photo of First Communion", "Bread and cup illustration", "Coloring sheet"],
        activities: ["Learn what happens at Mass when bread becomes Jesus", "Watch a video clip of First Communion", "Color a First Communion scene"],
        prayerFocus: "Jesus, I can't wait to receive you in Holy Communion.",
        takeHome: "Talk with your parents about preparing for your First Communion.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_1",
    program: "Elementary Faith Formation",
    unitNumber: 5,
    title: "Prayer",
    description: "First graders learn foundational Catholic prayers and develop a prayer life.",
    cccReference: "CCC 2558-2649",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Our Father",
        objective: "Students will memorize the Our Father and understand its meaning.",
        scriptureRef: "Matthew 6:9-13",
        cccParagraphs: "CCC 2759-2865",
        materials: ["Our Father prayer cards", "Illustrated Our Father booklet", "Pencils"],
        activities: ["Learn the Our Father line by line", "Discuss what each line means", "Practice reciting together"],
        prayerFocus: "Our Father, who art in heaven, hallowed be Thy name...",
        takeHome: "Pray the Our Father every night this week before bed.",
      },
      {
        lessonNumber: 2,
        title: "The Hail Mary",
        objective: "Students will learn the Hail Mary and understand Mary's role in our faith.",
        scriptureRef: "Luke 1:28",
        cccParagraphs: "CCC 2676-2677",
        materials: ["Rosary beads (one per student)", "Hail Mary prayer card", "Mary artwork"],
        activities: ["Learn the Hail Mary", "Learn about Mary's role as mother", "Hold and explore a rosary"],
        prayerFocus: "Hail Mary, full of grace, the Lord is with thee...",
        takeHome: "Teach your family the Hail Mary. Pray it together.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_1",
    program: "Elementary Faith Formation",
    unitNumber: 6,
    title: "Living Our Faith",
    description: "Students learn how to live as Catholic Christians in their daily lives.",
    cccReference: "CCC 1699-1802",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Two Great Commandments",
        objective: "Students will memorize and apply the Great Commandment in their relationships.",
        scriptureRef: "Matthew 22:37-40",
        cccParagraphs: "CCC 2052-2055",
        materials: ["Commandment poster", "Activity sheet", "Markers"],
        activities: ["Memorize Matthew 22:37-39", "Role-play loving God and neighbor", "Make a 'Love in Action' pledge card"],
        prayerFocus: "Lord, help me love you with my whole heart and love my neighbor as myself.",
        takeHome: "Do one act of love for a neighbor this week.",
      },
      {
        lessonNumber: 2,
        title: "Making Good Choices",
        objective: "Students will learn to use their conscience to make choices that please God.",
        scriptureRef: "Proverbs 3:5-6",
        cccParagraphs: "CCC 1776-1782",
        materials: ["Good choices scenario cards", "Traffic light craft (red/yellow/green)"],
        activities: ["Discuss scenarios: good choice or bad choice?", "Make a conscience 'traffic light' reminder", "Talk about asking God for help"],
        prayerFocus: "God, help me listen to my conscience and make good choices.",
        takeHome: "When you face a hard choice this week, stop and ask: 'Would Jesus be happy with this choice?'",
      },
    ],
  },

  // ===== GRADE 2 — First Communion Prep =====
  {
    gradeLevel: "GRADE_2",
    program: "First Communion Prep",
    unitNumber: 1,
    title: "The Creed — What We Believe",
    description: "Second graders learn the foundational beliefs of the Catholic faith: the Trinity, creation, and salvation.",
    cccReference: "CCC 185-1065",
    lessons: [
      {
        lessonNumber: 1,
        title: "God the Father",
        objective: "Students will know God the Father as almighty creator and loving parent.",
        scriptureRef: "John 3:16",
        cccParagraphs: "CCC 198-231",
        materials: ["Apostles' Creed card", "Bible", "Craft: paper scroll for the Creed"],
        activities: ["Learn the first article of the Creed", "Hear what 'almighty' means", "Begin memorizing the Creed"],
        prayerFocus: "I believe in God, the Father Almighty, Creator of heaven and earth...",
        takeHome: "Practice the first two lines of the Creed with your family every night.",
      },
      {
        lessonNumber: 2,
        title: "God the Son — Jesus Christ",
        objective: "Students will know Jesus as truly God and truly human, who died and rose for us.",
        scriptureRef: "John 1:14",
        cccParagraphs: "CCC 422-683",
        materials: ["Jesus timeline poster", "Creed card", "Colored pencils"],
        activities: ["Walk through the life of Jesus on a timeline", "Add to Creed memorization", "Draw one event from Jesus's life"],
        prayerFocus: "Jesus, Son of God and Son of Mary, I believe in you.",
        takeHome: "Continue memorizing the Creed. Quiz each other with your family.",
      },
      {
        lessonNumber: 3,
        title: "God the Holy Spirit and the Church",
        objective: "Students will know the role of the Holy Spirit and begin understanding the Church.",
        scriptureRef: "Acts 2:1-4",
        cccParagraphs: "CCC 683-1065",
        materials: ["Holy Spirit symbols poster", "Complete Creed card", "Poster board for class Creed"],
        activities: ["Finish the Creed", "Create a class 'We Believe' poster", "Recite the full Creed together"],
        prayerFocus: "I believe in the Holy Spirit, the holy catholic Church, the communion of saints...",
        takeHome: "Recite the entire Apostles' Creed to your parents from memory.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_2",
    program: "First Communion Prep",
    unitNumber: 2,
    title: "The Mass — Our Eucharistic Celebration",
    description: "Students learn the structure of the Mass and its meaning as the Church's central act of worship.",
    cccReference: "CCC 1345-1419",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Liturgy of the Word",
        objective: "Students will understand the first part of Mass and know that God speaks to us through Scripture.",
        scriptureRef: "Luke 4:21",
        cccParagraphs: "CCC 1346-1349",
        materials: ["Illustrated Mass booklet", "Reading ribbons (bookmark)", "Activity sheet"],
        activities: ["Walk through introductory rites and Liturgy of the Word", "Practice responses", "Identify the readings on a sample bulletin"],
        prayerFocus: "Lord, speak to my heart through your holy Word today.",
        takeHome: "At Mass, follow along with the readings. What was the Gospel about?",
      },
      {
        lessonNumber: 2,
        title: "The Liturgy of the Eucharist",
        objective: "Students will learn what happens during the Eucharistic Prayer when bread and wine become Jesus.",
        scriptureRef: "Luke 22:19-20",
        cccParagraphs: "CCC 1350-1405",
        materials: ["Last Supper illustration", "Mass booklet continued", "Blank bread/chalice cutouts"],
        activities: ["Re-enact the Last Supper story", "Learn the Consecration words", "Discuss Communion and how to receive"],
        prayerFocus: "Jesus, truly present in the Eucharist, I believe in you.",
        takeHome: "Explain to your parents what happens at the Consecration.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_2",
    program: "First Communion Prep",
    unitNumber: 3,
    title: "The Eucharist — Real Presence",
    description: "Students deepen their understanding of the Real Presence of Jesus in the Eucharist.",
    cccReference: "CCC 1373-1381",
    lessons: [
      {
        lessonNumber: 1,
        title: "This Is My Body",
        objective: "Students will believe that Jesus is truly present — Body, Blood, Soul, and Divinity — in the Eucharist.",
        scriptureRef: "John 6:51",
        cccParagraphs: "CCC 1374-1377",
        materials: ["John 6 Gospel page", "Eucharist activity sheet", "Sacred Host artwork"],
        activities: ["Read John 6:51-58 (adapted)", "Discuss 'real presence' in age-appropriate language", "Create a Eucharist reverence journal page"],
        prayerFocus: "Lord, I am not worthy that you should enter under my roof, but only say the word and my soul shall be healed.",
        takeHome: "Practice the 'Lord, I am not worthy' response. Share with your family what Real Presence means.",
      },
      {
        lessonNumber: 2,
        title: "Receiving Jesus Worthily",
        objective: "Students will learn how to receive Holy Communion with reverence and proper preparation.",
        scriptureRef: "1 Corinthians 11:27-29",
        cccParagraphs: "CCC 1384-1390",
        materials: ["Communion preparation checklist", "Practice run in church (if possible)"],
        activities: ["Practice the Communion procession", "Learn the proper way to receive", "Practice the Amen response"],
        prayerFocus: "Jesus, I receive you with love and respect. Please stay close to my heart.",
        takeHome: "Fast from snacks before Mass as a way to prepare your body for Jesus.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_2",
    program: "First Communion Prep",
    unitNumber: 4,
    title: "First Reconciliation — God's Forgiveness",
    description: "Students prepare for their First Reconciliation by learning about sin, conscience, and God's mercy.",
    cccReference: "CCC 1422-1498",
    lessons: [
      {
        lessonNumber: 1,
        title: "What Is Sin?",
        objective: "Students will understand sin as choosing to turn away from God's love.",
        scriptureRef: "Luke 15:11-24",
        cccParagraphs: "CCC 1849-1869",
        materials: ["Prodigal Son story", "Light/darkness illustrations", "Activity sheet"],
        activities: ["Hear the Prodigal Son parable", "Discuss mortal vs. venial sin in simple terms", "Identify ways we can say sorry to God"],
        prayerFocus: "Lord, I am sorry for my sins. Please forgive me.",
        takeHome: "Say an Act of Contrition with your family before bed.",
      },
      {
        lessonNumber: 2,
        title: "Examination of Conscience",
        objective: "Students will learn to examine their conscience using the Ten Commandments.",
        scriptureRef: "Exodus 20:1-17",
        cccParagraphs: "CCC 1454",
        materials: ["Child-friendly examination of conscience card", "Journal/notebook"],
        activities: ["Walk through examination of conscience together", "Write private reflections", "Practice the Act of Contrition"],
        prayerFocus: "O my God, I am heartily sorry for having offended Thee...",
        takeHome: "Practice examination of conscience each night before bed using the card.",
      },
      {
        lessonNumber: 3,
        title: "Steps of Confession",
        objective: "Students will know and practice the steps of the Sacrament of Reconciliation.",
        scriptureRef: "John 20:22-23",
        cccParagraphs: "CCC 1456-1460",
        materials: ["Confession step-by-step card", "Priest role-play props", "Reconciliation room diagram"],
        activities: ["Learn the 5 steps of Confession", "Role-play Confession in pairs", "Tour the reconciliation room at church"],
        prayerFocus: "God of mercy, thank you for always being ready to forgive me.",
        takeHome: "Memorize the Act of Contrition. Practice it with your parents.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_2",
    program: "First Communion Prep",
    unitNumber: 5,
    title: "The Ten Commandments",
    description: "Students learn the Ten Commandments as God's loving guidelines for life.",
    cccReference: "CCC 2052-2557",
    lessons: [
      {
        lessonNumber: 1,
        title: "Commandments 1-4: Loving God",
        objective: "Students will learn and apply the first four commandments about our relationship with God.",
        scriptureRef: "Deuteronomy 6:5",
        cccParagraphs: "CCC 2083-2195",
        materials: ["Ten Commandments poster", "Tablet craft supplies", "Activity sheet"],
        activities: ["Make stone tablet crafts", "Learn Commandments 1-4", "Discuss real-life applications"],
        prayerFocus: "Lord, help me love you above all things.",
        takeHome: "Memorize the first four commandments. Share with your family what they mean.",
      },
      {
        lessonNumber: 2,
        title: "Commandments 5-10: Loving Our Neighbor",
        objective: "Students will learn the commandments about treating others with love and justice.",
        scriptureRef: "Matthew 19:18-19",
        cccParagraphs: "CCC 2196-2557",
        materials: ["Ten Commandments booklet", "Scenario cards", "Activity sheet"],
        activities: ["Learn Commandments 5-10", "Sort scenarios: which commandment?", "Create a personal commandment pledge"],
        prayerFocus: "Lord, help me treat everyone with kindness and respect.",
        takeHome: "Memorize all Ten Commandments. Test yourself with your parents.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_2",
    program: "First Communion Prep",
    unitNumber: 6,
    title: "Prayer — Talking with God",
    description: "Students learn the four types of prayer and develop a deeper prayer life.",
    cccReference: "CCC 2626-2649",
    lessons: [
      {
        lessonNumber: 1,
        title: "Four Types of Prayer",
        objective: "Students will know adoration, thanksgiving, petition, and contrition as ways to pray.",
        scriptureRef: "Philippians 4:6",
        cccParagraphs: "CCC 2626-2649",
        materials: ["ACTS prayer acronym card", "Prayer journal", "Pencils/colored pencils"],
        activities: ["Learn ACTS: Adoration, Contrition, Thanksgiving, Supplication", "Write a personal ACTS prayer", "Share prayers with the class"],
        prayerFocus: "Lord, I adore you. I am sorry for my sins. Thank you for everything. Please help me...",
        takeHome: "Pray an ACTS prayer every night this week.",
      },
      {
        lessonNumber: 2,
        title: "Praying the Rosary",
        objective: "Students will learn the basics of the Rosary as a scriptural prayer.",
        scriptureRef: "Luke 1:28-30",
        cccParagraphs: "CCC 971, 2678",
        materials: ["Rosary beads", "Rosary guide card", "Rosary craft supplies (optional)"],
        activities: ["Learn how to pray the Rosary", "Pray one decade together", "Make a simple paper rosary craft"],
        prayerFocus: "Hail Mary, full of grace, the Lord is with thee...",
        takeHome: "Pray one decade of the Rosary with your family this week.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_2",
    program: "First Communion Prep",
    unitNumber: 7,
    title: "The Saints and Mary",
    description: "Students learn about Our Lady and the communion of saints as models and intercessors.",
    cccReference: "CCC 946-975",
    lessons: [
      {
        lessonNumber: 1,
        title: "Mary, Mother of God",
        objective: "Students will know Mary's role in salvation history and as our heavenly mother.",
        scriptureRef: "Luke 1:38",
        cccParagraphs: "CCC 963-972",
        materials: ["Mary's life timeline", "Art: Annunciation/Nativity/Pieta", "Blue ribbon craft"],
        activities: ["Walk through Mary's life", "Discuss how Mary said 'yes' to God", "Make a 'Be It Done Unto Me' banner"],
        prayerFocus: "Hail Holy Queen, mother of mercy, our life, our sweetness, and our hope...",
        takeHome: "Ask your parents about Mary. Say a Hail Mary together.",
      },
      {
        lessonNumber: 2,
        title: "Our Friends the Saints",
        objective: "Students will understand that saints are holy people who now live with God and pray for us.",
        scriptureRef: "Hebrews 12:1",
        cccParagraphs: "CCC 946-962",
        materials: ["Saint trading cards", "Patron saint research sheet", "Art supplies"],
        activities: ["Meet several saints through cards", "Research your patron saint or name saint", "Share one thing you admire about a saint"],
        prayerFocus: "(Student's patron saint), pray for me!",
        takeHome: "Learn about the saint you're named after or your patron saint. Share with your family.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_2",
    program: "First Communion Prep",
    unitNumber: 8,
    title: "Living as Disciples",
    description: "Students are called to live the Beatitudes and serve others as Jesus taught.",
    cccReference: "CCC 1716-1724",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Beatitudes",
        objective: "Students will know the Beatitudes as Jesus's path to true happiness.",
        scriptureRef: "Matthew 5:3-10",
        cccParagraphs: "CCC 1716-1724",
        materials: ["Beatitudes poster", "Activity matching sheet", "Poster board"],
        activities: ["Read the Beatitudes", "Match each Beatitude to a real-life example", "Create a class Beatitudes display"],
        prayerFocus: "Lord, show me how to live the Beatitudes in my life.",
        takeHome: "Pick one Beatitude and try to live it this week. Tell your parents how it went.",
      },
      {
        lessonNumber: 2,
        title: "Serving Others Like Jesus",
        objective: "Students will commit to service as an expression of discipleship.",
        scriptureRef: "Mark 10:45",
        cccParagraphs: "CCC 2443-2449",
        materials: ["Service project supplies", "Thank you note cards", "Photos of service"],
        activities: ["Complete a class service project (e.g., write cards to elderly parishioners)", "Discuss Works of Mercy", "Celebrate and pray for First Communion readiness"],
        prayerFocus: "Jesus, I want to serve you by serving others. Help me be generous.",
        takeHome: "Do one act of service at home this week as you prepare to receive Jesus for the first time.",
      },
    ],
  },

  // ===== GRADE 3 =====
  {
    gradeLevel: "GRADE_3",
    program: "Elementary Faith Formation",
    unitNumber: 1,
    title: "The Church",
    description: "Third graders explore the Church as the Body of Christ — its origins, marks, and mission.",
    cccReference: "CCC 748-975",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Church Jesus Founded",
        objective: "Students will know that Jesus founded the Catholic Church on Peter and the apostles.",
        scriptureRef: "Matthew 16:18",
        cccParagraphs: "CCC 763-769",
        materials: ["Church history timeline", "Picture of St. Peter's Basilica", "Colored pencils"],
        activities: ["Learn how Jesus called the apostles", "Trace the Church from Jesus to today", "Identify local parish leadership"],
        prayerFocus: "Lord, thank you for giving us the Church as a home for our faith.",
        takeHome: "Find out the name of your pastor and one thing he does for the parish.",
      },
      {
        lessonNumber: 2,
        title: "Four Marks of the Church",
        objective: "Students will know and explain the four marks: one, holy, catholic, and apostolic.",
        scriptureRef: "Ephesians 4:4-6",
        cccParagraphs: "CCC 811-870",
        materials: ["Four Marks poster", "Activity worksheet", "Markers"],
        activities: ["Learn each mark and what it means", "Find examples of each mark in parish life", "Make a Four Marks display"],
        prayerFocus: "I believe in one, holy, catholic, and apostolic Church.",
        takeHome: "Explain the four marks of the Church to your parents.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_3",
    program: "Elementary Faith Formation",
    unitNumber: 2,
    title: "Sacraments Overview",
    description: "Students learn about all seven sacraments as encounters with Jesus.",
    cccReference: "CCC 1113-1212",
    lessons: [
      {
        lessonNumber: 1,
        title: "What is a Sacrament?",
        objective: "Students will define sacrament as an outward sign instituted by Christ to give grace.",
        scriptureRef: "John 1:14",
        cccParagraphs: "CCC 1113-1134",
        materials: ["Sacrament signs poster", "Sign/symbol matching activity", "Colored pencils"],
        activities: ["Learn the definition of sacrament", "Match sacramental signs (water, oil, bread)", "Create a sacrament bookmark"],
        prayerFocus: "Jesus, thank you for giving us the sacraments so we can meet you.",
        takeHome: "Name all seven sacraments to your family.",
      },
      {
        lessonNumber: 2,
        title: "Sacraments of Healing",
        objective: "Students will understand Reconciliation and Anointing of the Sick as healing sacraments.",
        scriptureRef: "James 5:14-15",
        cccParagraphs: "CCC 1421-1532",
        materials: ["Sacrament booklet", "Oil of the Sick illustration", "Activity sheet"],
        activities: ["Learn about Reconciliation and Anointing", "Discuss when someone receives Anointing", "Write a prayer for the sick"],
        prayerFocus: "Lord, heal us in body and soul through your sacraments.",
        takeHome: "Ask your parents if they know someone who has received Anointing. Pray for that person.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_3",
    program: "Elementary Faith Formation",
    unitNumber: 3,
    title: "The Commandments",
    description: "A deeper exploration of the Ten Commandments and their application to third-grade life.",
    cccReference: "CCC 2052-2557",
    lessons: [
      {
        lessonNumber: 1,
        title: "God's Law of Love",
        objective: "Students will understand the commandments as expressions of God's love and care for us.",
        scriptureRef: "Deuteronomy 6:5-6",
        cccParagraphs: "CCC 2052-2082",
        materials: ["Stone tablet craft", "Commandment booklet", "Discussion scenario cards"],
        activities: ["Review all 10 commandments", "Apply them to school, home, parish", "Make a personal 'I Will' pledge card"],
        prayerFocus: "Lord, help me follow your commandments with a loving heart.",
        takeHome: "Memorize the Ten Commandments. Quiz your parents!",
      },
    ],
  },
  {
    gradeLevel: "GRADE_3",
    program: "Elementary Faith Formation",
    unitNumber: 4,
    title: "Conscience and Morality",
    description: "Students develop their understanding of conscience and moral decision-making.",
    cccReference: "CCC 1776-1802",
    lessons: [
      {
        lessonNumber: 1,
        title: "Forming a Good Conscience",
        objective: "Students will understand conscience as God's voice within us, guiding us to do good.",
        scriptureRef: "Romans 2:15",
        cccParagraphs: "CCC 1776-1794",
        materials: ["Conscience scenario cards", "Decision-making activity sheets"],
        activities: ["Define conscience in their own words", "Work through moral scenarios", "Role-play good and bad choices"],
        prayerFocus: "Holy Spirit, guide my conscience to always choose what is good and true.",
        takeHome: "Before making one decision this week, stop and ask your conscience: 'Is this right?'",
      },
    ],
  },
  {
    gradeLevel: "GRADE_3",
    program: "Elementary Faith Formation",
    unitNumber: 5,
    title: "The Liturgical Year",
    description: "Students explore the Church's liturgical calendar and its seasons.",
    cccReference: "CCC 1163-1178",
    lessons: [
      {
        lessonNumber: 1,
        title: "Seasons of the Church Year",
        objective: "Students will identify Advent, Christmas, Lent, Easter, and Ordinary Time.",
        scriptureRef: "Ecclesiastes 3:1",
        cccParagraphs: "CCC 1168-1173",
        materials: ["Liturgical calendar wheel", "Season colors chart", "Construction paper"],
        activities: ["Make a spinning liturgical calendar wheel", "Learn colors for each season", "Identify what we celebrate when"],
        prayerFocus: "Lord, help me grow closer to you through every season of the Church year.",
        takeHome: "What liturgical season is it now? What color does the priest wear?",
      },
    ],
  },
  {
    gradeLevel: "GRADE_3",
    program: "Elementary Faith Formation",
    unitNumber: 6,
    title: "Christian Living",
    description: "Students learn to live as disciples through works of mercy, service, and virtue.",
    cccReference: "CCC 2443-2449",
    lessons: [
      {
        lessonNumber: 1,
        title: "Works of Mercy",
        objective: "Students will learn the Corporal and Spiritual Works of Mercy and put them into practice.",
        scriptureRef: "Matthew 25:35-40",
        cccParagraphs: "CCC 2443-2449",
        materials: ["Works of Mercy chart", "Service project planning sheet", "Markers"],
        activities: ["Learn and memorize the Works of Mercy", "Plan a class service project", "Share ways to serve at home"],
        prayerFocus: "Lord, help me see your face in every person I serve.",
        takeHome: "Do one Corporal Work of Mercy this week. Journal about it.",
      },
    ],
  },

  // ===== GRADE 4 =====
  {
    gradeLevel: "GRADE_4",
    program: "Elementary Faith Formation",
    unitNumber: 1,
    title: "The Old Testament",
    description: "Students survey the Old Testament from Creation through the Patriarchs and Exodus.",
    cccReference: "CCC 101-141",
    lessons: [
      {
        lessonNumber: 1,
        title: "Abraham — Father of Faith",
        objective: "Students will know God's covenant with Abraham and how it continues today.",
        scriptureRef: "Genesis 12:1-3",
        cccParagraphs: "CCC 59-64",
        materials: ["Bible", "Map of Abraham's journey", "Activity sheet", "Colored pencils"],
        activities: ["Read Genesis 12 and 22", "Trace Abraham's journey on a map", "Discuss what faith means"],
        prayerFocus: "Lord, give me faith like Abraham to trust you even when it is hard.",
        takeHome: "Write about a time you trusted God even when it was scary.",
      },
      {
        lessonNumber: 2,
        title: "Moses and the Exodus",
        objective: "Students will learn the Exodus story as a model of God freeing us from slavery to sin.",
        scriptureRef: "Exodus 14:13-14",
        cccParagraphs: "CCC 1221-1222",
        materials: ["Exodus story illustrated book", "Passover symbols display", "Activity sheet"],
        activities: ["Watch/hear the Exodus story", "Connect the Passover to the Eucharist", "Map the Israelites' journey"],
        prayerFocus: "God of the Exodus, lead me out of sin and into your freedom.",
        takeHome: "Research what Catholics do during Holy Week to remember the Exodus/Passover.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_4",
    program: "Elementary Faith Formation",
    unitNumber: 2,
    title: "The Prophets",
    description: "Students learn about the major prophets and how they pointed toward Jesus.",
    cccReference: "CCC 64-66",
    lessons: [
      {
        lessonNumber: 1,
        title: "Isaiah — Seeing Jesus Coming",
        objective: "Students will see how Isaiah predicted Jesus hundreds of years before His birth.",
        scriptureRef: "Isaiah 9:6",
        cccParagraphs: "CCC 711-716",
        materials: ["Isaiah scroll craft", "Prophecy-fulfillment matching cards"],
        activities: ["Read Isaiah 9:6 and 53", "Match Old Testament prophecies to New Testament fulfillments", "Make an Isaiah scroll"],
        prayerFocus: "Lord, help me recognize you as the fulfillment of all God's promises.",
        takeHome: "Find Isaiah 9:6 in your Bible and share it with your family at dinner.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_4",
    program: "Elementary Faith Formation",
    unitNumber: 3,
    title: "Psalms and Wisdom",
    description: "Students explore the Psalms and wisdom literature as prayer and practical guidance.",
    cccReference: "CCC 304-305",
    lessons: [
      {
        lessonNumber: 1,
        title: "Praying with the Psalms",
        objective: "Students will use the Psalms as models of honest, heartfelt prayer.",
        scriptureRef: "Psalm 23:1",
        cccParagraphs: "CCC 2585-2589",
        materials: ["Psalm cards (Psalms 23, 51, 100, 139)", "Illuminated text art supplies"],
        activities: ["Pray Psalm 23 together", "Create illuminated manuscript art for a psalm verse", "Write their own psalm"],
        prayerFocus: "The Lord is my shepherd; I shall not want.",
        takeHome: "Pray Psalm 23 with your family this week.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_4",
    program: "Elementary Faith Formation",
    unitNumber: 4,
    title: "The New Testament",
    description: "Students explore the Gospels and letters of Paul as the fulfillment of God's promises.",
    cccReference: "CCC 124-127",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Four Gospels",
        objective: "Students will know the four evangelists and the unique perspective of each Gospel.",
        scriptureRef: "John 20:31",
        cccParagraphs: "CCC 125-127",
        materials: ["Gospel symbols chart (eagle, ox, lion, man)", "Evangelist symbol craft"],
        activities: ["Learn Matthew, Mark, Luke, John", "Match each Gospel to its symbol", "Read one unique passage from each Gospel"],
        prayerFocus: "Lord, open my heart to hear the Good News in all four Gospels.",
        takeHome: "Which evangelist is your favorite and why? Share at dinner.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_4",
    program: "Elementary Faith Formation",
    unitNumber: 5,
    title: "Acts of the Apostles",
    description: "Students follow the early Church from Pentecost through Paul's missionary journeys.",
    cccReference: "CCC 765-769",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Early Church Spreads",
        objective: "Students will learn how the apostles spread the Gospel after Pentecost.",
        scriptureRef: "Acts 1:8",
        cccParagraphs: "CCC 857-865",
        materials: ["Map of Paul's journeys", "Acts 2 reading", "Missionary journal activity"],
        activities: ["Map Paul's missionary journeys", "Read Acts 2:42-47 (early Christian community)", "Create a missionary journal entry"],
        prayerFocus: "Lord, give me courage to share my faith like the apostles did.",
        takeHome: "Research one apostle. How did they spread the Gospel? Share with your family.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_4",
    program: "Elementary Faith Formation",
    unitNumber: 6,
    title: "Church History",
    description: "Students survey 2,000 years of Church history, including saints and important moments.",
    cccReference: "CCC 748-809",
    lessons: [
      {
        lessonNumber: 1,
        title: "2,000 Years of Faith",
        objective: "Students will recognize key moments in Church history and see God's hand guiding the Church.",
        scriptureRef: "Matthew 28:20",
        cccParagraphs: "CCC 748-780",
        materials: ["Church history timeline display", "Marker/sticker dots", "Saint biography booklets"],
        activities: ["Build a class Church history timeline", "Place key events: Councils, saints, missions", "Present one era to the class"],
        prayerFocus: "Lord, you have been faithful to your Church for 2,000 years. Help me be faithful too.",
        takeHome: "Find one saint from Church history. What did they do for the Church?",
      },
    ],
  },

  // ===== GRADE 5 =====
  {
    gradeLevel: "GRADE_5",
    program: "Elementary Faith Formation",
    unitNumber: 1,
    title: "The Creed — Deep Dive",
    description: "Fifth graders revisit the Creed with deeper understanding of the Trinity, creation, and salvation.",
    cccReference: "CCC 185-1065",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Holy Trinity",
        objective: "Students will articulate the doctrine of the Trinity: three Persons, one God.",
        scriptureRef: "Matthew 28:19",
        cccParagraphs: "CCC 253-267",
        materials: ["Trinity diagrams (Shield of the Trinity)", "Discussion cards", "Notebook"],
        activities: ["Explore the Shield of the Trinity diagram", "Discuss the mystery of three-in-one", "Write their own explanation of the Trinity"],
        prayerFocus: "Glory be to the Father, and to the Son, and to the Holy Spirit...",
        takeHome: "Explain the Trinity to a younger sibling or friend.",
      },
      {
        lessonNumber: 2,
        title: "The Paschal Mystery",
        objective: "Students will understand the death and resurrection of Jesus as the central event of salvation.",
        scriptureRef: "1 Corinthians 15:3-4",
        cccParagraphs: "CCC 571-655",
        materials: ["Lenten calendar", "Holy Week timeline", "Reflection journal"],
        activities: ["Walk through Holy Week day by day", "Connect each event to the Creed", "Write a reflection on what the Resurrection means"],
        prayerFocus: "We proclaim your death, O Lord, and profess your resurrection, until you come again.",
        takeHome: "Research one Holy Week liturgy (Holy Thursday, Good Friday, Easter Vigil). Present to your family.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_5",
    program: "Elementary Faith Formation",
    unitNumber: 2,
    title: "Sacraments — Deep Dive",
    description: "Students explore all seven sacraments in depth, focusing on signs, matter, and form.",
    cccReference: "CCC 1113-1666",
    lessons: [
      {
        lessonNumber: 1,
        title: "Sacraments of Service",
        objective: "Students will understand Holy Orders and Matrimony as vocational sacraments.",
        scriptureRef: "Ephesians 5:25",
        cccParagraphs: "CCC 1534-1666",
        materials: ["Vocation booklet", "Interview questions for a priest or married couple"],
        activities: ["Learn about Holy Orders (deacon, priest, bishop)", "Discuss Matrimony as a sacrament", "Write interview questions for a priest or couple"],
        prayerFocus: "Lord, help me know and follow my vocation.",
        takeHome: "Interview a married couple or priest about their vocation. Share findings next class.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_5",
    program: "Elementary Faith Formation",
    unitNumber: 3,
    title: "Morality and Virtue",
    description: "Students learn the cardinal and theological virtues as tools for moral living.",
    cccReference: "CCC 1803-1845",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Virtues",
        objective: "Students will identify the four cardinal virtues and three theological virtues.",
        scriptureRef: "1 Corinthians 13:13",
        cccParagraphs: "CCC 1803-1845",
        materials: ["Virtue shield craft", "Virtue scenario cards", "Markers"],
        activities: ["Learn prudence, justice, fortitude, temperance", "Add faith, hope, and love", "Create personal virtue shields"],
        prayerFocus: "Lord, grant me the virtues I need to live a holy life.",
        takeHome: "Pick one virtue to practice this week. Journal about your experience.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_5",
    program: "Elementary Faith Formation",
    unitNumber: 4,
    title: "Catholic Social Teaching",
    description: "Students learn the principles of Catholic Social Teaching and how to apply them.",
    cccReference: "CCC 1877-1948",
    lessons: [
      {
        lessonNumber: 1,
        title: "Life and Dignity",
        objective: "Students will know that every human life is sacred from conception to natural death.",
        scriptureRef: "Jeremiah 1:5",
        cccParagraphs: "CCC 2258-2330",
        materials: ["Human dignity poster", "Life issues discussion cards"],
        activities: ["Discuss what 'sacred' means for human life", "Identify ways society respects/disrespects human dignity", "Write a reflection"],
        prayerFocus: "Lord, help me respect the dignity of every human person.",
        takeHome: "Find a news story that involves human dignity. Discuss with your family.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_5",
    program: "Elementary Faith Formation",
    unitNumber: 5,
    title: "Prayer and Worship",
    description: "Students develop a rich prayer life using many forms of Catholic prayer.",
    cccReference: "CCC 2650-2758",
    lessons: [
      {
        lessonNumber: 1,
        title: "Contemplative Prayer",
        objective: "Students will practice silent, contemplative prayer as listening to God.",
        scriptureRef: "1 Kings 19:12",
        cccParagraphs: "CCC 2709-2719",
        materials: ["Guided meditation script", "Candle", "Soft music", "Prayer journal"],
        activities: ["10 minutes of guided silent prayer", "Journal what they heard/felt", "Share (optional) with class"],
        prayerFocus: "Speak, Lord, your servant is listening.",
        takeHome: "Sit in silence for 5 minutes each day this week. Listen for God.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_5",
    program: "Elementary Faith Formation",
    unitNumber: 6,
    title: "Called to Serve",
    description: "Students explore vocation, discipleship, and service as responses to God's call.",
    cccReference: "CCC 871-945",
    lessons: [
      {
        lessonNumber: 1,
        title: "What Is a Vocation?",
        objective: "Students will understand vocation as God's personal call for each person's life.",
        scriptureRef: "Jeremiah 29:11",
        cccParagraphs: "CCC 871-945",
        materials: ["Vocation poster (priest, religious, married, single)", "Discernment journal"],
        activities: ["Learn about the four vocations", "Interview a parishioner about their vocation", "Begin a discernment journal"],
        prayerFocus: "Lord, what are you calling me to do with my life? Help me listen.",
        takeHome: "Pray daily this week: 'Lord, show me the vocation you have planned for me.'",
      },
    ],
  },

  // ===== GRADE 6 =====
  {
    gradeLevel: "GRADE_6",
    program: "Middle School Faith Formation",
    unitNumber: 1,
    title: "Old Testament Survey",
    description: "Sixth graders survey the entire Old Testament with attention to major themes and covenants.",
    cccReference: "CCC 54-64",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Pentateuch",
        objective: "Students will know the first five books of the Bible and their major themes.",
        scriptureRef: "Genesis 1:27",
        cccParagraphs: "CCC 54-64",
        materials: ["Bible", "Old Testament map", "Torah scrolls illustration", "Study guide"],
        activities: ["Survey Genesis through Deuteronomy", "Identify the covenants: Adam, Noah, Abraham, Moses", "Timeline activity"],
        prayerFocus: "Lord, speak to me through your ancient Word.",
        takeHome: "Read one chapter from Genesis and summarize it for your family.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_6",
    program: "Middle School Faith Formation",
    unitNumber: 2,
    title: "Covenant and Law",
    description: "Students explore the meaning of covenant in salvation history and God's law as gift.",
    cccReference: "CCC 2052-2082",
    lessons: [
      {
        lessonNumber: 1,
        title: "God Makes Covenants",
        objective: "Students will trace the major covenants and see how they culminate in Christ.",
        scriptureRef: "Jeremiah 31:31-34",
        cccParagraphs: "CCC 56-73",
        materials: ["Covenant chart", "Bible passages for each covenant", "Discussion questions"],
        activities: ["Map all major covenants", "Discuss how each points to the New Covenant", "Respond to: Why does God make covenants?"],
        prayerFocus: "Lord, thank you for your faithful covenant love that never gives up on us.",
        takeHome: "Which covenant do you find most meaningful and why? Write a paragraph.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_6",
    program: "Middle School Faith Formation",
    unitNumber: 3,
    title: "Prophets and Wisdom",
    description: "Students study the major and minor prophets and the wisdom books as guidance for life.",
    cccReference: "CCC 64-66",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Major Prophets",
        objective: "Students will know Isaiah, Jeremiah, Ezekiel, and Daniel and their key messages.",
        scriptureRef: "Isaiah 40:31",
        cccParagraphs: "CCC 702-716",
        materials: ["Prophet profile cards", "Bible passages", "Journal"],
        activities: ["Read key prophecies from each major prophet", "Discuss how they apply today", "Write a modern-day prophetic message"],
        prayerFocus: "Lord, give me courage to speak your truth like the prophets.",
        takeHome: "Read Isaiah 40:28-31 and memorize verse 31. Share it with your family.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_6",
    program: "Middle School Faith Formation",
    unitNumber: 4,
    title: "The Coming of Christ",
    description: "Students trace the prophecies, expectation, and preparation for the Messiah.",
    cccReference: "CCC 422-524",
    lessons: [
      {
        lessonNumber: 1,
        title: "Israel Awaits the Messiah",
        objective: "Students will understand the Jewish people's messianic expectation and how Jesus fulfilled it.",
        scriptureRef: "Isaiah 7:14",
        cccParagraphs: "CCC 437-444",
        materials: ["Messianic prophecy list", "Bible", "Study guide"],
        activities: ["Survey key messianic prophecies", "Match prophecy to New Testament fulfillment", "Discuss why Jesus's identity was controversial"],
        prayerFocus: "Come, Lord Jesus! We are waiting for you.",
        takeHome: "Find three messianic prophecies and their New Testament fulfillments.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_6",
    program: "Middle School Faith Formation",
    unitNumber: 5,
    title: "The Early Church",
    description: "Students follow the Church from Acts through the early centuries of martyrs and councils.",
    cccReference: "CCC 748-810",
    lessons: [
      {
        lessonNumber: 1,
        title: "Martyrs and Missionaries",
        objective: "Students will learn about early Christian martyrs and missionaries and their witness.",
        scriptureRef: "Revelation 2:10",
        cccParagraphs: "CCC 2473-2474",
        materials: ["Martyr stories (Stephen, Ignatius, Perpetua)", "Map of early Christian communities"],
        activities: ["Read stories of early martyrs", "Map the spread of early Christianity", "Write a letter as an early Christian"],
        prayerFocus: "Lord, give me the courage of the martyrs to stand up for my faith.",
        takeHome: "Research one early Christian martyr. Share their story at home.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_6",
    program: "Middle School Faith Formation",
    unitNumber: 6,
    title: "Faith in Action",
    description: "Students connect their faith to real-world action through service and advocacy.",
    cccReference: "CCC 1877-1948",
    lessons: [
      {
        lessonNumber: 1,
        title: "Catholic Social Teaching in Action",
        objective: "Students will identify a social issue and plan a faith-based response.",
        scriptureRef: "Matthew 25:40",
        cccParagraphs: "CCC 2419-2463",
        materials: ["CST principles card", "Service project planning guide", "Poster board"],
        activities: ["Identify a local social issue", "Apply a CST principle", "Plan and execute a class service project"],
        prayerFocus: "Lord, help me be your hands and feet in the world.",
        takeHome: "Complete one step of your service project at home this week.",
      },
    ],
  },

  // ===== GRADE 7 =====
  {
    gradeLevel: "GRADE_7",
    program: "Middle School Faith Formation",
    unitNumber: 1,
    title: "Jesus Christ: True God and True Man",
    description: "Seventh graders study Christology: who Jesus is, what He taught, and why it matters.",
    cccReference: "CCC 422-682",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Incarnation",
        objective: "Students will articulate that Jesus is fully human and fully divine (Hypostatic Union).",
        scriptureRef: "John 1:14",
        cccParagraphs: "CCC 464-483",
        materials: ["Christology overview", "Council of Nicaea context", "Reflection journal"],
        activities: ["Explore early heresies and why the Church defined the Incarnation", "Read Chalcedonian definition (simplified)", "Journal: Why does it matter that Jesus is fully human AND divine?"],
        prayerFocus: "Lord Jesus, truly God and truly man, draw me into your mystery.",
        takeHome: "Write a one-page reflection: What difference does it make that Jesus is fully human?",
      },
      {
        lessonNumber: 2,
        title: "The Teachings of Jesus",
        objective: "Students will summarize key teachings of Jesus — Kingdom, love, justice, forgiveness.",
        scriptureRef: "Matthew 5:17",
        cccParagraphs: "CCC 541-546",
        materials: ["Synoptic Gospel comparison chart", "Discussion questions", "Journal"],
        activities: ["Compare parables across Gospels", "Identify Jesus's core teachings", "Debate: What did Jesus mean by 'Kingdom of God'?"],
        prayerFocus: "Jesus, help me understand your Kingdom and live as a citizen of heaven.",
        takeHome: "Read the Sermon on the Mount (Matthew 5-7) this week.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_7",
    program: "Middle School Faith Formation",
    unitNumber: 2,
    title: "The Paschal Mystery",
    description: "Students explore the suffering, death, resurrection, and ascension of Jesus as the central mystery of faith.",
    cccReference: "CCC 571-667",
    lessons: [
      {
        lessonNumber: 1,
        title: "Why Did Jesus Have to Die?",
        objective: "Students will understand atonement and how Christ's sacrifice restores our relationship with God.",
        scriptureRef: "Romans 5:8",
        cccParagraphs: "CCC 606-618",
        materials: ["Stations of the Cross booklet", "Atonement theory overview", "Reflection journal"],
        activities: ["Pray the Stations of the Cross together", "Discuss: Why was sacrifice necessary?", "Write a personal reflection on one Station"],
        prayerFocus: "We adore you, O Christ, and we bless you, because by your Holy Cross, you have redeemed the world.",
        takeHome: "Pray the Stations of the Cross privately or with family this week.",
      },
      {
        lessonNumber: 2,
        title: "The Resurrection Changes Everything",
        objective: "Students will grasp why the Resurrection is the foundation of Christian faith.",
        scriptureRef: "1 Corinthians 15:17",
        cccParagraphs: "CCC 638-655",
        materials: ["Easter apparitions chart", "Discussion questions", "Journal"],
        activities: ["Survey resurrection appearances", "Discuss how resurrection changes our view of death", "Write a letter as if writing to a non-believer about the Resurrection"],
        prayerFocus: "Risen Lord, death has no power over us because of you. Alleluia!",
        takeHome: "Read 1 Corinthians 15:12-20. What is Paul's argument? Share with your family.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_7",
    program: "Middle School Faith Formation",
    unitNumber: 3,
    title: "The Church's Mission",
    description: "Students explore the nature and mission of the Church in the world today.",
    cccReference: "CCC 748-870",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Church as Sacrament",
        objective: "Students will understand that the Church is itself a sacrament — a sign of God's presence.",
        scriptureRef: "1 Peter 2:9",
        cccParagraphs: "CCC 774-776",
        materials: ["Church as sacrament overview", "Discussion questions", "Parish ministry directory"],
        activities: ["Discuss: How is the Church a sign of Christ in the world?", "Survey parish ministries", "Identify one ministry they want to join"],
        prayerFocus: "Lord, make your Church a clear sign of your love in our community.",
        takeHome: "Visit one parish ministry event or volunteer opportunity this month.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_7",
    program: "Middle School Faith Formation",
    unitNumber: 4,
    title: "Sacraments as Encounters with Christ",
    description: "Students mature in their understanding of the sacraments as personal encounters with the living Jesus.",
    cccReference: "CCC 1113-1212",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Eucharist: Source and Summit",
        objective: "Students will understand the Eucharist as the center and high point of Catholic life.",
        scriptureRef: "John 6:54",
        cccParagraphs: "CCC 1322-1419",
        materials: ["Eucharist theology overview", "Church documents excerpt (Sacrosanctum Concilium)", "Discussion questions"],
        activities: ["Read and discuss Vatican II quote on the Eucharist", "Attend Mass and write a reflection", "Discuss: How has my experience of Mass changed as I've grown?"],
        prayerFocus: "Lord Jesus, you are truly present in the Eucharist. I adore you.",
        takeHome: "Attend Mass this week with a notebook. Write one new insight about the Eucharist.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_7",
    program: "Middle School Faith Formation",
    unitNumber: 5,
    title: "The Moral Life",
    description: "Students explore Catholic moral theology, including human dignity, freedom, conscience, and sin.",
    cccReference: "CCC 1699-1876",
    lessons: [
      {
        lessonNumber: 1,
        title: "Freedom and Responsibility",
        objective: "Students will understand that true freedom means choosing the good, not just doing whatever we want.",
        scriptureRef: "Galatians 5:13",
        cccParagraphs: "CCC 1730-1748",
        materials: ["Freedom vs. license discussion cards", "Case studies", "Journal"],
        activities: ["Debate: Is freedom doing whatever you want?", "Analyze case studies using moral principles", "Write a personal definition of freedom"],
        prayerFocus: "Lord, free me from everything that keeps me from choosing what is truly good.",
        takeHome: "Write about a time you chose freedom for good rather than just 'doing whatever you wanted.'",
      },
    ],
  },
  {
    gradeLevel: "GRADE_7",
    program: "Middle School Faith Formation",
    unitNumber: 6,
    title: "Prayer and Spirituality",
    description: "Students develop a mature prayer life and explore different spiritualities within the Church.",
    cccReference: "CCC 2650-2758",
    lessons: [
      {
        lessonNumber: 1,
        title: "Schools of Spirituality",
        objective: "Students will be introduced to Benedictine, Franciscan, Dominican, and Ignatian spirituality.",
        scriptureRef: "Philippians 4:7",
        cccParagraphs: "CCC 2684-2685",
        materials: ["Spirituality comparison chart", "Sample Examen (Ignatian)", "Lectio Divina guide"],
        activities: ["Explore four different prayer traditions", "Try Lectio Divina with a Gospel passage", "Try the Examen at end of class"],
        prayerFocus: "Lord, show me the way to pray that best draws me close to you.",
        takeHome: "Try the Ignatian Examen each evening this week. Journal the results.",
      },
    ],
  },

  // ===== GRADE 8 — Confirmation Prep =====
  {
    gradeLevel: "GRADE_8",
    program: "Confirmation Prep",
    unitNumber: 1,
    title: "Who Is the Holy Spirit?",
    description: "8th graders explore the person and work of the Holy Spirit in Scripture, the Church, and their own lives.",
    cccReference: "CCC 683-747",
    lessons: [
      {
        lessonNumber: 1,
        title: "The Holy Spirit in Scripture",
        objective: "Students will trace the Holy Spirit through both Testaments, culminating in Pentecost.",
        scriptureRef: "Acts 2:1-11",
        cccParagraphs: "CCC 687-701",
        materials: ["Bible", "Holy Spirit in Scripture chart", "Highlight markers", "Journal"],
        activities: ["Survey Old Testament Spirit texts (creation, prophets)", "Read Acts 2:1-11 dramatically", "Chart the Spirit's work from Genesis to Pentecost"],
        prayerFocus: "Come, Holy Spirit, fill the hearts of your faithful and kindle in them the fire of your love.",
        takeHome: "Read Acts 2 fully. What would it have been like to be there?",
      },
      {
        lessonNumber: 2,
        title: "Gifts of the Holy Spirit",
        objective: "Students will name, define, and apply the seven gifts of the Holy Spirit to their lives.",
        scriptureRef: "Isaiah 11:2-3",
        cccParagraphs: "CCC 1830-1831",
        materials: ["Gifts of the Spirit handout", "Gift application scenario cards", "Colored pencils"],
        activities: ["Learn all 7 gifts: wisdom, understanding, counsel, fortitude, knowledge, piety, fear of the Lord", "Apply gifts to real teen situations", "Identify which gift they most need"],
        prayerFocus: "Holy Spirit, give me the gift of [wisdom/fortitude/etc.] I need most.",
        takeHome: "Interview your Confirmation sponsor: Which gift of the Spirit do they rely on most?",
      },
      {
        lessonNumber: 3,
        title: "Fruits of the Holy Spirit",
        objective: "Students will know the 12 fruits of the Spirit as evidence of the Spirit's presence in their lives.",
        scriptureRef: "Galatians 5:22-23",
        cccParagraphs: "CCC 1832",
        materials: ["Fruits of the Spirit poster", "Self-assessment inventory", "Journal"],
        activities: ["Learn the 12 fruits: charity, joy, peace, patience, kindness, goodness, generosity, gentleness, faithfulness, modesty, self-control, chastity", "Self-assess which fruits are strongest/weakest", "Set a goal for one fruit to grow"],
        prayerFocus: "Lord, grow the fruits of the Spirit in my life so others can see you in me.",
        takeHome: "Ask your parents: Which fruit of the Spirit do they see most in you? Pray about it.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_8",
    program: "Confirmation Prep",
    unitNumber: 2,
    title: "History of Confirmation",
    description: "Students trace Confirmation from the Acts of the Apostles through the Church's tradition.",
    cccReference: "CCC 1285-1321",
    lessons: [
      {
        lessonNumber: 1,
        title: "Confirmation in the Early Church",
        objective: "Students will see Confirmation as an apostolic practice from the very beginning of the Church.",
        scriptureRef: "Acts 8:14-17",
        cccParagraphs: "CCC 1285-1292",
        materials: ["Acts 8 passage", "Early Church document excerpts", "Timeline activity"],
        activities: ["Read Acts 8:14-17 and Acts 19:1-6", "Survey patristic quotes on Confirmation", "Create a Confirmation history timeline"],
        prayerFocus: "Lord, I am grateful to receive what the apostles passed on from the very beginning.",
        takeHome: "Research: What do the early Church Fathers say about Confirmation?",
      },
      {
        lessonNumber: 2,
        title: "The Bishop's Role",
        objective: "Students will understand why the bishop is the ordinary minister of Confirmation and what apostolic succession means.",
        scriptureRef: "2 Timothy 1:6",
        cccParagraphs: "CCC 1312-1314",
        materials: ["Apostolic succession diagram", "Bishop biography", "Q&A preparation guide"],
        activities: ["Learn the chain of apostolic succession", "Research your own bishop", "Prepare questions for a bishop Q&A session"],
        prayerFocus: "Lord, bless our bishop. May he be a faithful shepherd to our diocese.",
        takeHome: "Write a letter introducing yourself to the bishop who will confirm you.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_8",
    program: "Confirmation Prep",
    unitNumber: 3,
    title: "The Rite of Confirmation",
    description: "Students learn the ritual elements of Confirmation and what each one means.",
    cccReference: "CCC 1297-1301",
    lessons: [
      {
        lessonNumber: 1,
        title: "Choosing Your Confirmation Name",
        objective: "Students will research and choose a Confirmation saint name that reflects their faith journey.",
        scriptureRef: "Revelation 2:17",
        cccParagraphs: "CCC 2156-2159",
        materials: ["Saint biography resource book", "Research worksheet", "Reflection journal"],
        activities: ["Research 3 potential patron saints", "Journal: Why does this saint inspire me?", "Present saint choice to the class"],
        prayerFocus: "(Chosen saint), pray for me as I prepare for Confirmation.",
        takeHome: "Finalize your Confirmation saint choice and write a one-page reflection about why.",
      },
      {
        lessonNumber: 2,
        title: "The Sponsor's Role",
        objective: "Students will understand the role of their Confirmation sponsor and how to cultivate that relationship.",
        scriptureRef: "Proverbs 27:17",
        cccParagraphs: "CCC 1311",
        materials: ["Sponsor guidelines", "Interview questions sheet", "Letter-writing supplies"],
        activities: ["Learn sponsor qualifications and role", "Draft interview questions for sponsor", "Write a letter to your sponsor"],
        prayerFocus: "Lord, bless my sponsor. Help us grow in faith together.",
        takeHome: "Interview your Confirmation sponsor about their faith journey.",
      },
      {
        lessonNumber: 3,
        title: "Chrism, Laying on of Hands, and What They Mean",
        objective: "Students will understand the significance of chrism oil and the laying on of hands in Confirmation.",
        scriptureRef: "Isaiah 61:1",
        cccParagraphs: "CCC 1295-1301",
        materials: ["Chrism oil (show bottle)", "Rite of Confirmation text", "Reflection journal"],
        activities: ["Smell and see the chrism", "Read the words of Confirmation rite", "Reflect on being 'sealed with the gift of the Holy Spirit'"],
        prayerFocus: "Holy Spirit, seal me as your own on my Confirmation day.",
        takeHome: "Look up the full Rite of Confirmation. What word or phrase stands out to you and why?",
      },
    ],
  },
  {
    gradeLevel: "GRADE_8",
    program: "Confirmation Prep",
    unitNumber: 4,
    title: "The Creed — Deeper Dive",
    description: "Candidates revisit the articles of the Creed with mature understanding and personal appropriation.",
    cccReference: "CCC 185-1065",
    lessons: [
      {
        lessonNumber: 1,
        title: "Do I Really Believe This?",
        objective: "Students will personally engage each article of the Creed and articulate what they believe.",
        scriptureRef: "1 Peter 3:15",
        cccParagraphs: "CCC 185-197",
        materials: ["Apostles' Creed", "Personal Creed worksheet", "Journal"],
        activities: ["Read Creed line by line with discussion questions", "Identify any article they struggle to believe", "Write a personal Creed in their own words"],
        prayerFocus: "Lord, increase my faith where it is weak. I believe; help my unbelief.",
        takeHome: "Memorize the Nicene Creed. Be ready to recite it next class.",
      },
      {
        lessonNumber: 2,
        title: "Defending the Faith",
        objective: "Students will practice basic apologetics — explaining and defending Catholic beliefs.",
        scriptureRef: "1 Peter 3:15",
        cccParagraphs: "CCC 50-73",
        materials: ["Common questions about Catholicism cards", "CCC reference guide"],
        activities: ["Work through top 10 questions non-Catholics ask", "Prepare a 30-second explanation of one doctrine", "Present and get feedback from peers"],
        prayerFocus: "Lord, give me wisdom and courage to explain my faith clearly and charitably.",
        takeHome: "Practice explaining the Real Presence to a friend who doesn't believe it.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_8",
    program: "Confirmation Prep",
    unitNumber: 5,
    title: "Moral Decision-Making",
    description: "Students develop tools for making moral decisions using conscience, Scripture, and Church teaching.",
    cccReference: "CCC 1776-1802",
    lessons: [
      {
        lessonNumber: 1,
        title: "Forming a Mature Conscience",
        objective: "Students will learn the Church's teaching on conscience formation and follow it in moral decisions.",
        scriptureRef: "Romans 2:15",
        cccParagraphs: "CCC 1776-1802",
        materials: ["Conscience formation guide", "Moral case studies", "STOP framework card"],
        activities: ["Learn the STOP framework (Scripture, Tradition, Others, Prayer)", "Work through moral case studies", "Debate: When does conscience override authority?"],
        prayerFocus: "Holy Spirit, form my conscience to recognize truth and choose the good.",
        takeHome: "Apply the STOP framework to a moral dilemma you are facing. Journal about it.",
      },
      {
        lessonNumber: 2,
        title: "Sin, Mercy, and Reconciliation",
        objective: "Students will understand grave sin, its effects, and the healing power of Reconciliation.",
        scriptureRef: "Luke 15:20",
        cccParagraphs: "CCC 1849-1876",
        materials: ["Examination of conscience for teens", "Reconciliation guide", "Prayer booklet"],
        activities: ["Review the examination of conscience for teens", "Discuss: Why is Reconciliation before Confirmation important?", "Participate in or schedule group Reconciliation"],
        prayerFocus: "O my God, I am heartily sorry for having offended Thee...",
        takeHome: "Go to Confession before your Confirmation. Bring your examination of conscience card.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_8",
    program: "Confirmation Prep",
    unitNumber: 6,
    title: "Service and Discipleship",
    description: "Students complete their service hours and reflect on service as a way of living out Confirmation.",
    cccReference: "CCC 2443-2449",
    lessons: [
      {
        lessonNumber: 1,
        title: "Corporal Works of Mercy",
        objective: "Students will know and practice the seven Corporal Works of Mercy.",
        scriptureRef: "Matthew 25:35-40",
        cccParagraphs: "CCC 2447",
        materials: ["Works of Mercy poster", "Service hour log sheets", "Reflection journal"],
        activities: ["Learn/review the 7 Corporal Works", "Share service hour experiences", "Identify which Work their service most represents"],
        prayerFocus: "Lord, when I serve the least of these, help me see your face.",
        takeHome: "Complete and submit your service hour logs. Reflect on what God taught you through service.",
      },
      {
        lessonNumber: 2,
        title: "Spiritual Works of Mercy",
        objective: "Students will know the seven Spiritual Works of Mercy and practice them in peer relationships.",
        scriptureRef: "James 5:20",
        cccParagraphs: "CCC 2447",
        materials: ["Spiritual Works of Mercy card", "Peer accountability guide"],
        activities: ["Learn the 7 Spiritual Works", "Role-play: How to admonish a sinner charitably", "Discuss: Who can you 'bear wrongs patiently' for this week?"],
        prayerFocus: "Lord, help me be a spiritual support to my friends and family.",
        takeHome: "Identify one Spiritual Work of Mercy you will practice this week and journal about the experience.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_8",
    program: "Confirmation Prep",
    unitNumber: 7,
    title: "Prayer and Relationship with God",
    description: "Students develop a personal, mature prayer life through Lectio Divina, the Liturgy of the Hours, and contemplative prayer.",
    cccReference: "CCC 2650-2758",
    lessons: [
      {
        lessonNumber: 1,
        title: "Lectio Divina",
        objective: "Students will practice the four steps of Lectio Divina as a way to pray with Scripture.",
        scriptureRef: "Psalm 1:2",
        cccParagraphs: "CCC 2708",
        materials: ["Lectio Divina guide", "Gospel passage (e.g., John 15:1-17)", "Journal", "Candle"],
        activities: ["Practice all four steps: Lectio, Meditatio, Oratio, Contemplatio", "Share insights (optional)", "Journal response to God's word"],
        prayerFocus: "Speak, Lord; your servant is listening. Your words are spirit and life.",
        takeHome: "Pray Lectio Divina once this week with the passage from Mark 1:9-13.",
      },
      {
        lessonNumber: 2,
        title: "The Liturgy of the Hours",
        objective: "Students will understand the Church's daily prayer cycle and pray Morning or Evening Prayer together.",
        scriptureRef: "Psalm 141:2",
        cccParagraphs: "CCC 1174-1178",
        materials: ["Christian Prayer book (or app)", "Psalm selections", "Prayer schedule"],
        activities: ["Learn what the Liturgy of the Hours is", "Pray Evening Prayer together", "Discuss: How can I build prayer into my daily schedule?"],
        prayerFocus: "God, come to my assistance. Lord, make haste to help me.",
        takeHome: "Download a Liturgy of the Hours app and pray one Hour this week.",
      },
    ],
  },
  {
    gradeLevel: "GRADE_8",
    program: "Confirmation Prep",
    unitNumber: 8,
    title: "Living as a Confirmed Catholic",
    description: "The final unit prepares candidates to go forth as confirmed disciples — living stewardship, evangelization, and a lifelong faith.",
    cccReference: "CCC 900-945",
    lessons: [
      {
        lessonNumber: 1,
        title: "Stewardship: Time, Talent, and Treasure",
        objective: "Students will understand stewardship as a lifestyle response to God's gifts.",
        scriptureRef: "Matthew 25:14-30",
        cccParagraphs: "CCC 2402-2406",
        materials: ["Stewardship pledge card", "Parable of the Talents text", "Talent assessment inventory"],
        activities: ["Read Parable of the Talents and apply it today", "Identify their God-given talents", "Fill out a personal stewardship pledge card"],
        prayerFocus: "Lord, everything I have is yours. Show me how to use my gifts for your glory.",
        takeHome: "Fill out your stewardship pledge card and share it with your parents.",
      },
      {
        lessonNumber: 2,
        title: "You Are Called to Evangelize",
        objective: "Students will know that every confirmed Catholic is called to share the Good News.",
        scriptureRef: "Matthew 28:19-20",
        cccParagraphs: "CCC 905-913",
        materials: ["Evangelization scenarios", "Personal faith story worksheet", "Missionary discipleship guide"],
        activities: ["Learn the 'New Evangelization'", "Write their personal faith story (3 minutes)", "Practice sharing faith in pairs"],
        prayerFocus: "Lord, give me the courage to share your love with everyone I meet.",
        takeHome: "Share your personal faith story with one friend or family member before Confirmation day.",
      },
      {
        lessonNumber: 3,
        title: "Confirmation Day: What Happens Next?",
        objective: "Students will be prepared for the Confirmation rite and committed to an ongoing faith life after Confirmation.",
        scriptureRef: "Philippians 1:6",
        cccParagraphs: "CCC 1302-1305",
        materials: ["Confirmation rite program", "Post-Confirmation commitment card", "Letters from sponsors"],
        activities: ["Walk through the Confirmation rite step by step", "Receive letters from sponsors", "Write a post-Confirmation faith commitment"],
        prayerFocus: "Lord, what you have begun in me, bring to completion. I say YES to being your disciple.",
        takeHome: "Come to Confirmation ready to say yes to God with your whole heart.",
      },
    ],
  },
];

async function main() {
  console.log("📚 Seeding Catholic curriculum...\n");

  let unitCount = 0;
  let lessonCount = 0;

  for (const unit of curriculum) {
    const { lessons, ...unitData } = unit;

    const createdUnit = await prisma.curriculumUnit.upsert({
      where: {
        gradeLevel_program_unitNumber: {
          gradeLevel: unitData.gradeLevel as any,
          program: unitData.program,
          unitNumber: unitData.unitNumber,
        },
      },
      update: {},
      create: {
        gradeLevel: unitData.gradeLevel as any,
        program: unitData.program,
        unitNumber: unitData.unitNumber,
        title: unitData.title,
        description: unitData.description,
        cccReference: unitData.cccReference,
      },
    });

    unitCount++;

    for (const lesson of lessons) {
      await prisma.lesson.upsert({
        where: {
          unitId_lessonNumber: {
            unitId: createdUnit.id,
            lessonNumber: lesson.lessonNumber,
          },
        },
        update: {},
        create: {
          unitId: createdUnit.id,
          lessonNumber: lesson.lessonNumber,
          title: lesson.title,
          objective: lesson.objective,
          scriptureRef: lesson.scriptureRef,
          cccParagraphs: lesson.cccParagraphs,
          materials: JSON.stringify(lesson.materials),
          activities: JSON.stringify(lesson.activities),
          prayerFocus: lesson.prayerFocus,
          takeHome: lesson.takeHome,
          durationMinutes: lesson.durationMinutes ?? 60,
        },
      });
      lessonCount++;
    }

    console.log(`✅ ${unitData.gradeLevel} — Unit ${unitData.unitNumber}: ${unitData.title} (${lessons.length} lessons)`);
  }

  // Add sample service hours for 8th grade Confirmation students
  console.log("\n⏱ Adding sample service hour records...");

  const grade8Students = await prisma.student.findMany({
    where: { gradeLevel: "GRADE_8" },
  });

  const serviceHourData = [
    {
      description: "Volunteered at Holy Face Parish Food Pantry",
      hours: 4,
      date: new Date("2025-10-12"),
      verified: true,
      verifiedBy: "Susan Beall",
    },
    {
      description: "Helped with Fall Festival setup and cleanup",
      hours: 3.5,
      date: new Date("2025-11-02"),
      verified: true,
      verifiedBy: "Susan Beall",
    },
    {
      description: "Tutored younger children at after-school program",
      hours: 5,
      date: new Date("2025-12-07"),
      verified: false,
      verifiedBy: null,
    },
  ];

  for (const student of grade8Students) {
    for (const sh of serviceHourData) {
      await prisma.serviceHour.create({
        data: {
          studentId: student.id,
          date: sh.date,
          hours: sh.hours,
          description: sh.description,
          verified: sh.verified,
          verifiedBy: sh.verifiedBy ?? undefined,
        },
      });
    }
    console.log(`✅ Added service hours for ${student.firstName} ${student.lastName}`);
  }

  // Update academic year in class records
  console.log("\n📅 Updating academic year to 2025-2026...");
  const updated = await prisma.class.updateMany({
    where: { academicYear: "2024-2025" },
    data: { academicYear: "2025-2026" },
  });
  console.log(`✅ Updated ${updated.count} class records to 2025-2026`);

  console.log(`\n🎉 Curriculum seed complete!`);
  console.log(`   📖 ${unitCount} curriculum units created`);
  console.log(`   📝 ${lessonCount} lessons created`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
